[
    {
        "@id": "http://www.wikidata.org/entity/Q18462097",
        "type": "Feature",
        "properties": {
            "title": "Calamona",
            "summary": "Human settlement in Italy",
            "reciprocal": false
        },
        "links": [
            {
                "type": "closeMatch",
                "identifier": "https://www.geonames.org/8955441"
            },
            {
                "type": "closeMatch",
                "identifier": "https://pleiades.stoa.org/places/682534"
            }
        ]
    }
]